RED = \033[1;31m
GREEN = \033[1;32m
YELLOW = \033[1;33m
BLUE = \033[1;34m
BLACK = \033[0;39m

NAME = config
CPP = c++
FLAGS = -Wall -Wextra -Werror -MMD -std=c++98 -fsanitize=address
RM = rm -f

SRC =  main.cpp ServerConfig.cpp ParsingConfig.cpp LocationConfig.cpp
F_OBJ = obj/
OBJ = $(addprefix $(F_OBJ), $(SRC:.cpp=.o))
DEP = $(addprefix $(F_OBJ), $(SRC:.cpp=.d))

$(F_OBJ)%.o: %.cpp Makefile
	$(CPP) $(FLAGS) -I ./ -c $< -o $@

all: dir $(NAME)

dir:
	@mkdir -p $(F_OBJ)

-include $(DEP)
$(NAME): $(OBJ)
	$(CPP) $(FLAGS) -I ./ $(OBJ) -o $(NAME)
	@echo "$(GREEN)Everything has been compilated.$(BLACK)"

clean:
	$(RM) $(OBJ) $(DEP)
	$(RM) -R obj

fclean: clean
	$(RM) $(NAME)
	@echo "$(YELLOW)Everything has been cleaned.$(BLACK)"

re: fclean all

.PHONY: all clean fclean re dir

